# Common build stage
FROM node:18-alpine3.18 as common-build-stage

COPY . ./app

WORKDIR /app

RUN npm install
RUN npm install -g typescript

EXPOSE 4210

#Dvelopment build stage
FROM common-build-stage as development-build

ENV NODE_ENV development

CMD ["npm", "run", "dev"]
